### ISSUE TITLE
Error after upgrading to 1.1.12

### ISSUE THREAD

**Issue by scotthellewell** [chymz/ng2-ckeditor#174]
When webpacking my Angular app, I get the following error when going to version 1.1.12 from 1.1.7.

ERROR in Error: Error encountered resolving symbol values statically. Could not resolve ng2-ckeditor/lib relative to ~snipped path~/app.module.ts., resolving symbol AppModule in ~snipped path~/app.module.ts, resolving symbol AppModule in ~snipped path~/app.module.ts

~snipped path~/boot-aot.ts(5,36): error TS2307: Cannot find module './app/app.module.ngfactory'.

Going back to version 1.1.7 resolves the issue.  I had previously used "^1.1.7" in my package.json, and after several hours spent, I finally figured out that it was an update to ng2-ckeditor that was causing my problems.  My development machines were still on the older version, but the build server automatically gets the latest everytime.

**Comment by chymz** [comment]
I will try a new version with this variables : https://github.com/chymz/ng2-ckeditor/blob/master/tsconfig-aot.json#L24-L25 set to `false`

**Comment by scotthellewell** [comment]
Cool, I will let you know if that helps.

**Comment by chymz** [comment]
I've published v1.1.13

**Comment by kzimny** [comment]
Version 1.1.13 works for me on local machine and on production server with AoT compilation.

**Comment by scotthellewell** [comment]
It worked for me as well.  Thanks for the quick response yesterday.
