### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by brankoiliccc** [chymz/ng2-ckeditor#217]
You plan on supporting angular 6 ?

**Comment by kzimny** [comment]
Do you experience any problems with angular6 and ng2-ckeditor? The [demo ](https://stackblitz.com/edit/ng2-ckeditor) version works fine with angular6.

**Comment by brankoiliccc** [comment]
It does work fine but 

1. Doing npm install spits warning
```
npm WARN ng2-ckeditor@1.2.0 requires a peer of @angular/core@^5.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.0 requires a peer of @angular/forms@^5.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-ckeditor@1.2.0 requires a peer of @angular/common@^5.0.5 but none is installed. You must install peer dependencies yourself.
```

2. Requires rxjs-compat to run. If i just use "rxjs": "6.2.0" 
ng build spits error 

`ERROR in node_modules/ng2-completer/src/services/completer-base-data.d.ts(1,10): error TS2305: Module '"../node_modules/rxjs/Subject"' has no exported member 'Subject'.
node_modules/ng2-completer/src/services/completer-data.d.ts(2,10): error TS2305: Module '".../node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng2-completer/src/services/completer-service.d.ts(1,10): error TS2305: Module '"../node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/ng2-completer/src/services/local-data.d.ts(2,10): error TS2305: Module '"../node_modules/rxjs/Observable"' has no exported member 'Observable'.
node_modules/rxjs/Observable.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Observable'.
node_modules/rxjs/Subject.d.ts(1,15): error TS2307: Cannot find module 'rxjs-compat/Subject'.`

**Comment by kzimny** [comment]
Forgot about the warnings, this should be corrected in the next version. Everything works fine. The error doesn't come from ng2-ckeditor, it seems to be an other component. I'm working with angular version 6.0.4, no problems here.

**Comment by brankoiliccc** [comment]
Ya sorry about that lol. The second error was related to ng2-completer not ng2-ckeditor.
